stureplansgruppen:
  target: dev
  outputs:
    dev:
      type: databricks
      database: spgt # Catalog i Databricks
      schema: dbt_dev_sturep #Schema i Databricks
      host: "{{ env_var('dbtDatabricksConnectHOST') }}"
      http_path: "{{ env_var('dbtDatabricksConnectHTTP') }}" #http patch till compute
      token: "{{ env_var('dbtDatabricksConnect') }}" # Token genereras i DATABRICKS SETTINGS/developer/tokens och läggs i .env i dbt projektet
      auth_type: databricks_cli
      threads: 4

